print("Welcome to the Band Name Generator")
city = input("Whats the name of the city you grew up in? : \n")
print(city)
pet = input("Whats you pets name : \n")
print(pet)
print("Your band name is" + " " + city + " " + pet)
